base_config: ./config/
base_expid: FCNv1_KDD12
dataset_id: KDD12_x10

tuner_space:
    model_root: './checkpoints/'
    batch_size: 10000
    exp_num_layers: [6, 7, 8, 9, 10]
    lin_num_layers: [4, 5, 6, 7, 8]