base_config: ./config/
base_expid: FCNv1_iPinYou_x1_csv
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    embedding_regularizer: [1.e-3]
    exp_num_layers: [2, 3, 4, 5]
    lin_num_layers: [2, 3, 4, 5]
    net_dropout: [0.1, 0.2, 0.3]