base_config: ./config/
base_expid: FCNv1_ML_1M
dataset_id: ML_1M_7_x1

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    exp_num_layers: [1, 2, 3, 4, 5]
    lin_num_layers: [1, 2, 3, 4, 5]
    net_dropout: [0.1]