base_config: ./config/
base_expid: FCNv2_iPinYou_x1_csv
dataset_id: iPinYou_x1_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    exp_num_layers: [2, 3, 4]
    lin_num_layers: [0, 1, 2]
    net_dropout: [0.1, 0.2, 0.3]