base_config: ./config/
base_expid: LCN_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    batch_size: 8192
    num_cross_layers: [1, 2, 3, 4, 5, 6, 8]
    net_dropout: [0.1]