Base:
    model_root: './checkpoints/'
    num_workers: 8
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

ECN_Avazu:
    model: ECN
    dataset_id: Avazu_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_cross_layers: 4
    net_dropout: 0
    num_heads: 3
    layer_norm: True
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    early_stop_patience: 1
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_Avazu:
    model: FCNv1
    dataset_id: Avazu_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    exp_num_layers: 3
    lin_num_layers: 1
    net_dropout: 0
    batch_norm: True
    num_heads: 4
    epochs: 100
    shuffle: True
    seed: 2025
    early_stop_patience: 1
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv2_Avazu:
    model: FCNv2
    dataset_id: Avazu_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    exp_num_layers: 4
    lin_num_layers: 4
    net_dropout: 0
    batch_norm: True
    num_heads: 4
    epochs: 100
    shuffle: True
    seed: 2025
    early_stop_patience: 1
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ECN_full_Criteo: # This is a config template
    model: ECN_full
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 16
    num_cross_layers: 4
    net_dropout: 0.1
    num_heads: 1
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ECN_Criteo: # This is a config template
    model: ECN
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 16
    num_cross_layers: 4
    net_dropout: 0.1
    num_heads: 1
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

LCN_Criteo: # This is a config template
    model: LCN
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 16
    num_cross_layers: 4
    net_dropout: 0.1
    num_heads: 1
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_Criteo:
    model: FCNv1
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 16
    exp_num_layers: 4
    lin_num_layers: 5
    net_dropout: 0.1
    batch_norm: False
    num_heads: 1
    epochs: 1
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_full_Criteo:
    model: FCNv1_full
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 16
    exp_num_layers: 4
    lin_num_layers: 5
    net_dropout: 0.1
    batch_norm: False
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv2_Criteo:
    model: FCNv2
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 16
    exp_num_layers: 4
    lin_num_layers: 1
    net_dropout: 0.1
    batch_norm: False
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ECN_ML_1M_7_x1: # This is a config template
    model: ECN
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-2
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_cross_layers: 4
    net_dropout: 0.1
    num_heads: 1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_ML_1M:
    model: FCNv1
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-2
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    exp_num_layers: 3
    lin_num_layers: 1
    net_dropout: 0.1
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv2_ML_1M:
    model: FCNv2
    dataset_id: ML_1M_7_x1
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-2
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    exp_num_layers: 2
    lin_num_layers: 3
    net_dropout: 0.1
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 20250517
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ECN_KDD12_x10: # This is a config template
    model: ECN
    dataset_id: KDD12_x10
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_cross_layers: 6
    net_dropout: 0
    num_heads: 1
    batch_norm: True
    layer_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_KDD12:
    model: FCNv1
    dataset_id: KDD12_x10
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-7
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    exp_num_layers: 4
    lin_num_layers: 4
    net_dropout: 0
    batch_norm: True
    layer_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv2_KDD12:
    model: FCNv2
    dataset_id: KDD12_x10
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-7
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    exp_num_layers: 4
    lin_num_layers: 1
    net_dropout: 0
    batch_norm: True
    layer_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ECN_full_KKBox_csv: # This is a config template
    model: ECN_full
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_cross_layers: 4
    net_dropout: 0.2
    num_heads: 1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

ECN_KKBox_csv: # This is a config template
    model: ECN
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_cross_layers: 8
    net_dropout: 0.2
    num_heads: 1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

LCN_KKBox_csv: # This is a config template
    model: LCN
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    num_cross_layers: 4
    net_dropout: 0.2
    num_heads: 1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_full_KKBox_csv:
    model: FCNv1_full
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    exp_num_layers: 4
    lin_num_layers: 4
    net_dropout: 0.2
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_KKBox_csv:
    model: FCNv1
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    exp_num_layers: 4
    lin_num_layers: 4
    net_dropout: 0.2
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv2_KKBox_csv:
    model: FCNv2
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    exp_num_layers: 4
    lin_num_layers: 0
    net_dropout: 0.2
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv2_KKBox_csv2:
    model: FCNv2
    dataset_id: KKBox_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 5.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 128
    exp_num_layers: 0
    lin_num_layers: 4
    net_dropout: 0.2
    batch_norm: True
    num_heads: 1
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'


ECN_iPinYou_x1_csv: # This is a config template
    model: ECN
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    num_cross_layers: 4
    net_dropout: 0.1
    num_heads: 1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv1_iPinYou_x1_csv:
    model: FCNv1
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    exp_num_layers: 4
    lin_num_layers: 3
    net_dropout: 0.2
    batch_norm: True
    layer_norm: False
    num_heads: 2
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'

FCNv2_iPinYou_x1_csv:
    model: FCNv2
    dataset_id: iPinYou_x1_csv
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-3
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 16
    exp_num_layers: 0
    lin_num_layers: 4
    net_dropout: 0.3
    batch_norm: True
    layer_norm: False
    num_heads: 2
    epochs: 100
    shuffle: True
    seed: 2024
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'